CREATE TABLE admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   creation_date TIMESTAMP WITHOUT TIME ZONE,
   modified_date TIMESTAMP WITHOUT TIME ZONE,
   active BOOLEAN NOT NULL,
   can_manage_products BOOLEAN NOT NULL,
   can_manage_users BOOLEAN NOT NULL,
   can_manage_orders BOOLEAN NOT NULL,
   can_manage_stores BOOLEAN NOT NULL,
   super_admin BOOLEAN NOT NULL,
   can_manage_admins BOOLEAN NOT NULL,
   CONSTRAINT pk_admins PRIMARY KEY (id)
);

ALTER TABLE admins ADD CONSTRAINT uc_admins_email UNIQUE (email);