CREATE TABLE addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   creation_date TIMESTAMP WITHOUT TIME ZONE,
   modified_date TIMESTAMP WITHOUT TIME ZONE,
   active BOOLEAN NOT NULL,
   name VARCHAR(255),
   zipcode VARCHAR(8),
   city VARCHAR(100),
   state VARCHAR(2),
   street VARCHAR(150),
   number VARCHAR(20),
   country VARCHAR(100),
   complement VARCHAR(100),
   customer_id BIGINT,
   CONSTRAINT pk_addresses PRIMARY KEY (id)
);

ALTER TABLE addresses ADD CONSTRAINT FK_ADDRESSES_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);
