CREATE TABLE IF NOT EXISTS product_category (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   creation_date TIMESTAMP WITHOUT TIME ZONE,
   modified_date TIMESTAMP WITHOUT TIME ZONE,
   active BOOLEAN NOT NULL,
   category_id BIGINT,
   product_id BIGINT,
   CONSTRAINT pk_product_category PRIMARY KEY (id)
);

ALTER TABLE product_category ADD CONSTRAINT FK_PRODUCT_CATEGORY_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE product_category ADD CONSTRAINT FK_PRODUCT_CATEGORY_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE product_category
ADD CONSTRAINT unique_product_category
UNIQUE (category_id, product_id);